### PR TITLE
Fixed homepage in gemspec

### PR DESCRIPTION
**Pull request by bogdan**

### CODE REVIEW

**Comment by asaaki** [comment]
+1 for this fix!

**Comment by schneems** [comment]
:+1: this is a minor change and is pointing at the correct homepage. This should be merged in, or followed up with reasons why it is not a valid PR.

**Comment by carlosantoniodasilva** [comment]
Shouldn't that be http**s**?

**Comment by rafaelfranca** [comment]
This is already fixed. Closing this one

**Pull request closed without merging**
