### PR TITLE
update copyright year to range

### PR DESCRIPTION
**Pull request by PatrickJS**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Ok. One pull request was good, two I could merge, but I don't think you should go on each rails repository and send it. I'll do when we release the gem.

Thanks

**Comment by PatrickJS** [comment]
sorry my copyright node.js bot found this repo

**Comment by rafaelfranca** [comment]
No problem

**Comment by PatrickJS** [comment]
k all rails repos were set to opt-out

**Pull request closed without merging**
