### PR TITLE
add license information to the gemspec

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
This way we can get this info when using rubygems.org api

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Journey was merged inside Rails so I think we don't need to add this

**Comment by jordimassaguerpla** [comment]
Sure? I mean journey is still distributed as a separate gem, right?

**Comment by rafaelfranca** [comment]
Not the version corresponding to the master branch

**Comment by jordimassaguerpla** [comment]
ok. I did not know journey had been merge to rails master branch.

**Comment by jordimassaguerpla** [comment]
thanks for the clarification

**Pull request closed without merging**
